### PR TITLE
rename: exmple_transformation_for to example_transform_for

### PR DESCRIPTION
**Pull request by D-Alex**
fix inconsistent nameing

### CODE REVIEW

**Comment by goldhoorn** [comment]
Does it also affect the RC? (does it need to patched in the RC)

**Comment by goldhoorn** [comment]
Just checked the RC and master full install these methods are nowhere used, so okay for merge. Patch for RC <b> IS </b> needed. (recommend patch even this PR is small AND causes a API change)

**Comment by doudou** [comment]
Pushed to rock-rc as well.

**Comment by jmachowinski** [comment]
Wtf ? Even if this is a bugfix, I am still the maintainer of this package.

**Pull request merged**
